$(document).ready(function(){
    $("#designer").click(function(){
        $("#designer").hide();
        $("#designing").show();
    });
});
$(document).ready(function(){
    $("#designing").click(function(){
        $("#designing").hide();
        $("#designer").show();
    });
});
$(document).ready(function(){
    $("#developer").click(function(){
        $("#developer").hide();
        $("#developing").show();
    });
});
$(document).ready(function(){
    $("#developing").click(function(){
        $("#developing").hide();
        $("#developer").show();
    });
});
